#!/usr/bin/env python3
import logging
import sys

logger = logging.getLogger(__name__)

try:
    from simplygo.CryptLib import CryptLib
    print(CryptLib().encrypt(sys.argv[1]))
except ModuleNotFoundError:
    logger.exception("Did you install simplygo module?")
except Exception:
    logger.exception("Unable to encrypt input.")
